version: "3.3"
services:
  api:
    build: .
    container_name: api
    hostname: api
    ports:
      - "8080:8080"
#    environment:
#      - VIRTUAL_HOST=host.docker.internal
#      - VIRTUAL_PORT=8080
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.shoppiem_backend.rule=Host(`api.shoppiem.com`)"
#      - "traefik.http.routers.shoppiem_backend.service=shoppiem_backend"
#      - "traefik.http.services.shoppiem_backend.loadbalancer.server.port=8080"
    networks:
      - proxy_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /tmp:/tmp

networks:
  proxy_network:
    driver: bridge

