/* tslint:disable */
/* eslint-disable */

/**
 * This file is generated by core-types-ts on behalf of typeconv, DO NOT EDIT.
 * For more information, see:
 *  - {@link https://github.com/grantila/core-types-ts}
 *  - {@link https://github.com/grantila/typeconv}
 */


/** Author */
export interface Author {

  /** Author.name */
  name: string;

  /** Author.image */
  image: string;

  /** Author.designation */
  designation: string;
}


/** ResponsePayload */
export interface ResponsePayload {

  /** ResponsePayload.id */
  id: number;

  /** ResponsePayload.title */
  title: string;

  /** ResponsePayload.paragraph */
  paragraph: string;

  /** ResponsePayload.image */
  image: string;
  author: Author;

  /** ResponsePayload.tags */
  tags: string[];

  /** ResponsePayload.publishDate */
  publishDate: string;
}


/** RequestPayload */
export interface RequestPayload {

  /** RequestPayload.id */
  id: number;

  /** RequestPayload.title */
  title: string;

  /** RequestPayload.paragraph */
  paragraph: string;

  /** RequestPayload.image */
  image: string;
  author: Author;

  /** RequestPayload.tags */
  tags: string[];

  /** RequestPayload.publishDate */
  publishDate: string;
}
