version: '3.8'
services:
  function_hub_db:
    image: postgres
    command: postgres -c 'max_connections=2000'
    container_name: function_hub_db
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=function_hub
    ports:
      - "8432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/