version: '3.8'
services:
  fh_proxy:
    image: mitmproxy/mitmproxy
    container_name: fh_proxy
    command: mitmweb --web-host 0.0.0.0 --web-port 8081 -s /data/scripts/redirect.py -s /data/scripts/modify_response.py
    restart: always
    volumes:
      - ./proxy:/data
      - ~/.mitmproxy:/home/mitmproxy/.mitmproxy
    ports:
      - "7070:8080"
      - "7071:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  runtime:
    build: .
    container_name: runtime
    restart: always
    volumes:
      - ./deno-dir:/deno-dir
      - ~/.mitmproxy:/.mitmproxy
    ports:
      - "8000:8000"
    environment:
      - NODE_EXTRA_CA_CERTS=.mitmproxy/mitmproxy-ca.pem
      - DENO_NO_PROMPT=1
      - HTTP_PROXY=host.docker.internal:7070
      - HTTPS_PROXY=host.docker.internal:7070
      - NO_PROXY=host.docker.internal,registry.npmjs.org
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    privileged: true
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
